const $=s=>document.querySelector(s); let account,system,view={kind:"system"},editing=false,draft=null;
class ApiError extends Error{constructor(r,m){super(m);this.status=r.status}}
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",...options,headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{}),...options.headers}});if(r.status===401){location.assign(`/login?returnTo=${encodeURIComponent(location.pathname)}`);throw new ApiError(r,"Session expired")};if(!r.ok){let m="Something went wrong.";try{m=(await r.json()).message||m}catch{}throw new ApiError(r,m)}return r.status===204?null:r.json()}
const esc=v=>{const n=document.createElement("span");n.textContent=v??"";return n.innerHTML}; const initials=n=>(n||"?").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();
function toast(m,bad=false){const t=$("#toast");t.textContent=m;t.className=bad?"show error":"show";setTimeout(()=>t.className="",3000)}
async function refresh(){system=await api(`/api/systems/${account.systemId}`);renderSidebar();render()}
function renderSidebar(){ $("#systemName").textContent=system.displayName; const a=$("#systemAvatar");a.innerHTML=system.logo?`<img src="${esc(system.logo)}" alt="">`:"✦";const q=$("#memberSearch").value.toLowerCase();$("#memberList").innerHTML=system.members.filter(m=>m.name.toLowerCase().includes(q)).map(m=>`<button data-member="${m.id}" class="member-item ${view.memberId===m.id?"selected":""}">${m.avatar?`<img class="avatar" src="${esc(m.avatar)}" alt="">`:`<span class="avatar" style="--color:${m.color}">${esc(initials(m.name))}</span>`}<span><strong>${esc(m.name)}</strong><small>${esc(m.pronouns||"Pronouns not set")}</small></span></button>`).join("")||"<p>No members yet.</p>"}
function field(label,name,value,type="text",help=""){return `<label class="field"><span>${label}</span>${editing?(type==="textarea"?`<textarea name="${name}">${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}">`):`<output>${esc(value)||"Not set"}</output>`}${help?`<small>${help}</small>`:""}</label>`}
function imageField(label,name,url,help){return `<section class="field image-field"><span>${label}</span><button type="button" ${editing?`data-image="${name}"`:"disabled"} aria-label="${editing?`Change ${label}`:label}">${url?`<img src="${esc(url)}" alt="${label}">`:`<span class="image-empty">No image</span>`}</button>${help?`<small>${help}</small>`:""}</section>`}
function editButton(){return `<button id="editApply" class="primary">${editing?"✅ Apply changes":"📝 Edit"}</button>`}
function renderSystem(){const d=draft||system;$("#content").innerHTML=`<header class="page-head"><div><p class="eyebrow">SYSTEM INFORMATION</p><h1>${esc(system.displayName)}</h1></div>${editButton()}</header><form id="profileForm" class="profile-grid">${imageField("System logo","logo",d.logo)}${field("System name","displayName",d.displayName)}${field("Description","description",d.description,"textarea")}${field("System tag","tag",d.tag)}${editing?`<label class="check"><input type="checkbox" name="showSystemTag" ${d.showSystemTag?"checked":""}> Show system tag</label>`:`<div class="field"><span>Show system tag</span><output>${d.showSystemTag?"Yes":"No"}</output></div>`}${imageField("System banner","banner",d.banner,"Landscape images around 6:4 work best.")}</form><p id="saveError" class="error-message"></p>`}
function nextFormName(forms){let i=0,n=new Set(forms.map(f=>f.displayName));while(n.has(`Custom form ${i}`))i++;return `Custom form ${i}`}
function formStrip(m,selected){return `<div class="strip"><fieldset><legend>Voice playback</legend>${[["🔈","Off","off"],["💽","Send","send"]].map(x=>`<button data-playback="${x[2]}" class="${m.voice.playback===x[2]?"selected":""}" aria-label="${x[1]} voice playback"><b>${x[0]}</b>${x[1]}</button>`).join("")}<button disabled aria-label="Browser playback coming soon"><b>🖥️</b>Browser<small>Coming soon</small></button><button disabled aria-label="Both playback coming soon"><b>🔊</b>Both<small>Coming soon</small></button><details><summary>Voice settings</summary><p>Replace and delete voice are unavailable until voice management is supported.</p></details></fieldset><fieldset><legend>Forms / somas</legend><div class="forms">${m.forms.map(f=>`<span class="form-chip ${selected?.id===f.id?"selected":""}"><button data-form="${f.id}">${esc(f.displayName)}${m.defaultFormId===f.id?" ★ Default":""}</button><button data-delete-form="${f.id}" aria-label="Delete form ${esc(f.displayName)}">❌</button></span>`).join("")}<button id="addForm">➕ Add another form…</button></div></fieldset></div>`}
function renderMember(){const m=system.members.find(x=>x.id===view.memberId);if(!m){view={kind:"system"};return renderSystem()}const selected=m.forms.find(f=>f.id===view.formId)||m.forms.find(f=>f.id===m.defaultFormId)||m.forms[0];view.formId=selected?.id;const d=draft||m;$("#content").innerHTML=`${formStrip(m,selected)}<header class="page-head"><h1>${esc(m.name)}</h1><div class="actions">${editButton()}<button id="deleteMember" class="danger">❌ Delete member</button></div></header><form id="profileForm"><section class="profile-grid">${imageField("Picture / Avatar","avatar",d.avatar)}${field("Member name","name",d.name)}${field("Color","color",d.color,"color")}${field("Pronouns","pronouns",d.pronouns)}${field("Description","description",d.description,"textarea")}${field("Aliases","alias",d.alias,"text","A short optional name used to find this member.")}${field("Proxy prefix","prefix",d.prefix)}${field("Proxy suffix","suffix",d.suffix)}${imageField("Member banner","banner",d.banner,"Landscape images around 6:4 work best.")}</section>${selected?formSection(selected):"<section class='form-profile'><h2>No forms yet</h2><p>Add a form above when this member needs another presentation.</p></section>"}</form><p id="saveError" class="error-message"></p>`}
function formSection(f){const d=(draft&&draft.form)||f;return `<section class="form-profile"><div class="section-head"><div><p class="eyebrow">SELECTED FORM</p><h2>${esc(f.displayName)}</h2></div>${editing?"<span class='editing'>Editing with member</span>":""}</div><div class="profile-grid">${imageField("Form picture","form.picture",d.picture)}${field("Form name","form.displayName",d.displayName)}${field("Pronouns","form.pronouns",d.pronouns)}${field("Description / Soma","form.soma",d.soma,"textarea")}${field("Form proxy prefix","form.prefix",d.prefix)}${field("Form proxy suffix","form.suffix",d.suffix)}${imageField("Form banner","form.banner",d.banner,"Portrait images around 4:8 work best.")}</div></section>`}
function render(){editing=false;draft=null;view.kind==="system"?renderSystem():renderMember();renderSidebar();$("#content").focus()}
function values(){const fd=new FormData($("#profileForm")),o={};for(const [k,v] of fd){if(k.startsWith("form.")){(o.form??={})[k.slice(5)]=v||null}else o[k]=v||null}if(view.kind==="system")o.showSystemTag=fd.has("showSystemTag");return o}
async function save(){const o=values(),m=system.members.find(x=>x.id===view.memberId);draft={...draft,...o,form:o.form?{...(draft?.form||{}),...o.form}:draft?.form};try{if(view.kind==="system")await api(`/api/systems/${system.id}`,{method:"PATCH",body:JSON.stringify(o)});else{delete o.form;await api(`/api/systems/${system.id}/members/${m.id}`,{method:"PATCH",body:JSON.stringify(o)});if(draft.form&&view.formId)await api(`/api/systems/${system.id}/members/${m.id}/forms/${view.formId}`,{method:"PATCH",body:JSON.stringify(draft.form)})}await refresh();toast("Changes applied") }catch(e){$("#saveError").textContent="Couldn't save those changes. Your edits are still here.";toast("Couldn't save. Your edits are still here.",true);console.error(e)}}
function confirmDelete(title,text,label){return new Promise(resolve=>{const d=$("#confirmDialog");$("#confirmTitle").textContent=title;$("#confirmText").textContent=text;$("#confirmDelete").textContent=label;d.showModal();d.onclose=()=>resolve(d.returnValue==="confirm")})}
document.addEventListener("click",async e=>{const member=e.target.closest("[data-member]");if(member){view={kind:"member",memberId:member.dataset.member};render();return}if(e.target.closest("#systemButton")){view={kind:"system"};render();return}if(e.target.closest("#editApply")){if(!editing){editing=true;const m=system.members.find(x=>x.id===view.memberId);draft=structuredClone(view.kind==="system"?system:{...m,form:m?.forms.find(f=>f.id===view.formId)});view.kind==="system"?renderSystem():renderMember()}else save();return}const img=e.target.closest("[data-image]");if(img){const key=img.dataset.image,cur=key.startsWith("form.")?draft.form[key.slice(5)]:draft[key];$("#imageUrl").value=cur||"";$("#imagePreview").src=cur||"";$("#imageDialog").dataset.key=key;$("#imageDialog").showModal();return}const fs=e.target.closest("[data-form]");if(fs){view.formId=fs.dataset.form;editing=false;draft=null;renderMember();return}const del=e.target.closest("[data-delete-form]");if(del){const m=system.members.find(x=>x.id===view.memberId),f=m.forms.find(x=>x.id===del.dataset.deleteForm);if(await confirmDelete(`Delete the form “${f.displayName}”?`,"The member will not be deleted.","Delete form")){await api(`/api/systems/${system.id}/members/${m.id}/forms/${f.id}`,{method:"DELETE"});await refresh()}return}if(e.target.closest("#deleteMember")){const m=system.members.find(x=>x.id===view.memberId);if(await confirmDelete(`Delete member “${m.name}”?`,"This MEMBER and all associated forms will be permanently removed.","Delete member")){await api(`/api/systems/${system.id}/members/${m.id}`,{method:"DELETE"});view={kind:"system"};await refresh()}return}if(e.target.closest("#addForm")){const m=system.members.find(x=>x.id===view.memberId),f=await api(`/api/systems/${system.id}/members/${m.id}/forms`,{method:"POST",body:JSON.stringify({displayName:nextFormName(m.forms)})});await refresh();view={kind:"member",memberId:m.id,formId:f.id};editing=true;draft={...system.members.find(x=>x.id===m.id),form:f};renderMember();return}const pb=e.target.closest("[data-playback]");if(pb){const m=system.members.find(x=>x.id===view.memberId);await api(`/api/systems/${system.id}/members/${m.id}`,{method:"PATCH",body:JSON.stringify({playback:pb.dataset.playback})});await refresh();toast(`Voice playback set to ${pb.textContent.trim()}`)}});
$("#imageUrl").addEventListener("input",e=>$("#imagePreview").src=e.target.value);$("#imageApply").addEventListener("click",()=>{const key=$("#imageDialog").dataset.key,v=$("#imageUrl").value||null;if(key.startsWith("form."))draft.form[key.slice(5)]=v;else draft[key]=v;setTimeout(()=>view.kind==="system"?renderSystem():renderMember())});
$("#addMember").onclick=async()=>{const proxy=prompt("Choose a proxy prefix for the new member (required):");if(!proxy)return;try{const m=await api(`/api/systems/${system.id}/members`,{method:"POST",body:JSON.stringify({name:"New member",proxy})});await refresh();view={kind:"member",memberId:m.id};editing=true;draft=structuredClone(system.members.find(x=>x.id===m.id));renderMember()}catch(e){toast(e.message,true)}};$("#memberSearch").oninput=renderSidebar;$("#logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.assign("/login")};
(async()=>{try{account=await api("/api/account");if(!account.systemId)throw Error("No system is linked to this account.");await refresh();$("#loading").hidden=true;$("#app").hidden=false}catch(e){if(e.status!==401){$("#loading").innerHTML=`<h1>Dashboard unavailable</h1><p>${esc(e.message)}</p>`}}})();
